### ISSUE TITLE
MCC2 does not respond when wrong baudrate is set

### ISSUE THREAD

**Issue by labuserMBI** [dschick/pytango-PhytronMCC2#2]
commit b0155bb changed the default value of the baudrate property from 115200 to 57600, which leads to previously working MCC2 controllers not responding anymore.
Looks like MCC2 can only operate at a single fixed baudrate. We need to check if either the baudrate of the controller can be changed (especially in older firmware revisions), or if we should revert this back to 115200. What was the reason for going to 57600?

**Comment by dschick** [comment]
Actually 57600 is the default baudrate of the MCC2 modules.
We have typically used the higher 115200 baudrate in order to increase communication speed.
However, we noticed, that this is not the limiting factor and we have been able to solve speed issue with some other reprogramming done in [release v2.0.0](https://github.com/MBI-Div-B/pytango-PhytronMCC2/tree/v2.0.0)
